services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: training_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: training_tracker_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://trainer:securepassword@db:5432/training_tracker
      JWT_SECRET: change-me-in-production
      FRONTEND_URL: http://localhost:3000
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: "false"
      SMTP_USER: sashireddy7997@gmail.com
      SMTP_PASS: jgmseoyjlngingyn
      SMTP_FROM: Training Tracker <sashireddy7997@gmail.com>
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: training_tracker_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
